### ISSUE TITLE
Please upload the new CF release

### ISSUE THREAD

**Issue by pblittle** [cloudfoundry-community/community-shared-boshreleases#2]
@longnguyen11288, your CF release uploads are incredibly useful. If you have time, and it isn't too much trouble, do you mind building and uploading the latest CF release?

**Comment by longnguyen11288** [comment]
Will do, building/uploading now, if you have newer version of bosh you can use http://bosh.io/

**Comment by pblittle** [comment]
@longnguyen11288 thanks for the upload and the pointer. I knew about the new website, but I didn't realize CF tarballs were available.

**Comment by longnguyen11288** [comment]
Yup

**Comment by pblittle** [comment]
@longnguyen11288, I see you bumped the `admin-ui-boshrelease` and added the mysql blobs. You just made my day. :smile:

**Comment by longnguyen11288** [comment]
hey @pblittle I've uploaded v202 and 201 of CF :D

**Comment by longnguyen11288** [comment]
Just added v5 to community bosh shared release
